// NAVIGATION QUẢN LÝ NHÂN SỰ
export const TITLE_NAVIGATION_QUANLYNHANSU ="QUẢN LÝ NHÂN SỰ";
export const STRING_NAVIGATION_QUANLYNHANSU ="HOME-QUẢN LÝ NHÂN SỰ-NHÂN SỰ PHÁT TRIẾN PHẦN MỀM";

// NAVIGATION QUẢN LÝ NHÂN SỰ
// SỮA FILE EXPORT
export const TITLE_NAVIGATION_TEAM ="QUẢN LÝ ĐỘI NHÓM";
//Quan lý task
export const TITLE_NAVIGATION_TASK="DANH SÁCH CÔNG VIỆC";


